- shell:
    - command: pip3 install --upgrade -r bin/requirements.txt
      stdout: true
      description: Install dependencies for scripts in ~/bin

    - command: pip3 install --upgrade -r manifest/tools-requirements.txt
      stdout: true
      description: Install dev tools with Pip
