repos:
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/life4/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.1.0
    hooks:
      - id: beautysh
        args: [--force-function-style, paronly]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.19.0
    hooks:
      - id: toml-sort
        args: [--in-place]
